### ISSUE TITLE
Can't build 'assistant' on Thunder

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/assistant#1]
I had some issue building prbz-overview, that lead me to build locally assistant. I'm no expert but I think there might be something wrong the both project build config. Anyhow, to try to solve that I've add a job on Thunder for assistant but this one is also not building (for similar reason as I had locally):

https://thunder.sin2.redhat.com/jenkins/job/assistant/1/console

**Comment by soul2zimate** [comment]
Fixed by commit https://github.com/jboss-set/assistant/commit/d1efa0bd0e8022c98a607f41dd963ae904a2a770
https://thunder.sin2.redhat.com/jenkins/job/assistant/2/ is good now.
I also removed the "site" goal and added my email into the notification list
